try:
    from enum import StrEnum
except ImportError:
    from enum import Enum
    class StrEnum(str, Enum):
        pass


class MemoryDomain(StrEnum): SESSION = "SESSION"; PERSONAL = "PERSONAL"; OPERATIONAL = "OPERATIONAL"
class Sensitivity(StrEnum): ORDINARY = "ORDINARY"; PERSONAL = "PERSONAL"; SENSITIVE = "SENSITIVE"; PROHIBITED = "PROHIBITED"
class SemanticType(StrEnum): DECISION = "DECISION"; CONSTRAINT = "CONSTRAINT"; PREFERENCE = "PREFERENCE"; PERSONAL_STATE = "PERSONAL_STATE"; PERSONAL_FACT = "PERSONAL_FACT"; HEALTH_CLAIM = "HEALTH_CLAIM"; EXPERIENCE = "EXPERIENCE"; RELATIONSHIP = "RELATIONSHIP"; CREDENTIAL = "CREDENTIAL"; TEMPORARY_EVENT = "TEMPORARY_EVENT"; OTHER = "OTHER"
class TemporalScope(StrEnum): INSTANT = "INSTANT"; SESSION = "SESSION"; TEMPORARY = "TEMPORARY"; DURABLE = "DURABLE"; UNKNOWN = "UNKNOWN"
class PersistenceIntent(StrEnum): NONE = "NONE"; IMPLICIT = "IMPLICIT"; EXPLICIT = "EXPLICIT"; EXPLICIT_TEMPORARY = "EXPLICIT_TEMPORARY"; FORGET_REQUEST = "FORGET_REQUEST"
class RestrictionLevel(StrEnum): NONE = "NONE"; POTENTIALLY_SENSITIVE = "POTENTIALLY_SENSITIVE"; NEVER_DURABLE = "NEVER_DURABLE"
class PolicyDecision(StrEnum): SESSION_ONLY = "SESSION_ONLY"; PROHIBITED = "PROHIBITED"; PERSIST = "PERSIST"; PERSIST_MINIMIZED = "PERSIST_MINIMIZED"; DEFER = "DEFER"; PURGE_REQUEST = "PURGE_REQUEST"
class EvidenceStatus(StrEnum): STAGED = "STAGED"; ACTIVE = "ACTIVE"; ABORTED = "ABORTED"; PURGE_REVOKED = "PURGE_REVOKED"; PURGED = "PURGED"
class PayloadStatus(StrEnum): STAGED = "STAGED"; ACTIVE = "ACTIVE"; PURGE_PENDING = "PURGE_PENDING"; DESTROYED = "DESTROYED"; ABORTED = "ABORTED"
class RecordStatus(StrEnum): ACTIVE = "ACTIVE"; SUPERSEDED = "SUPERSEDED"; RETRACTED = "RETRACTED"; PURGE_REVOKED = "PURGE_REVOKED"; PURGED = "PURGED"
class Lifetime(StrEnum): SESSION = "SESSION"; TEMPORARY = "TEMPORARY"; DURABLE = "DURABLE"
class PatchOperationType(StrEnum): ADD = "ADD"; SUPERSEDE = "SUPERSEDE"; RETRACT = "RETRACT"; LINK = "LINK"; FLAG_CONFLICT = "FLAG_CONFLICT"; RESOLVE_CONFLICT = "RESOLVE_CONFLICT"; PURGE_REQUEST = "PURGE_REQUEST"
class PatchStatus(StrEnum): PROPOSED = "PROPOSED"; VALIDATED = "VALIDATED"; AUDIT_ACCEPTED = "AUDIT_ACCEPTED"; AUDIT_REJECTED = "AUDIT_REJECTED"; DEFERRED = "DEFERRED"; STALE = "STALE"; COMMITTED = "COMMITTED"; ABORTED = "ABORTED"
class AuditDecision(StrEnum): ACCEPT = "ACCEPT"; REJECT = "REJECT"; DEFER = "DEFER"
class ConflictStatus(StrEnum): OPEN = "OPEN"; RESOLVED = "RESOLVED"
class LeaseStatus(StrEnum): VALID = "VALID"; REVOKED = "REVOKED"; EXPIRED = "EXPIRED"
class PurgeStatus(StrEnum): PURGE_REQUESTED = "PURGE_REQUESTED"; PURGE_IN_PROGRESS = "PURGE_IN_PROGRESS"; PURGE_COMPLETE = "PURGE_COMPLETE"; PURGE_FAILED = "PURGE_FAILED"
class MountDecision(StrEnum): ALLOW = "ALLOW"; DENY = "DENY"
class SubjectKind(StrEnum): USER = "USER"; THIRD_PARTY = "THIRD_PARTY"; SYSTEM = "SYSTEM"; UNKNOWN = "UNKNOWN"
class Polarity(StrEnum): AFFIRMED = "AFFIRMED"; NEGATED = "NEGATED"; UNKNOWN = "UNKNOWN"
class Modality(StrEnum): FACTUAL = "FACTUAL"; HYPOTHETICAL = "HYPOTHETICAL"; QUOTED = "QUOTED"; UNCERTAIN = "UNCERTAIN"; UNKNOWN = "UNKNOWN"
class DetectionLayer(StrEnum): INGRESS_GUARD = "INGRESS_GUARD"; MEMORY_ANALYZER = "MEMORY_ANALYZER"; SEGMENTER = "SEGMENTER"; PERSISTENCE_POLICY = "PERSISTENCE_POLICY"; EVIDENCE_SANITIZER = "EVIDENCE_SANITIZER"; PATCH_VALIDATOR = "PATCH_VALIDATOR"; EVIDENCE_RESOLVER = "EVIDENCE_RESOLVER"; AUDITOR = "AUDITOR"; COMMIT_VALIDATOR = "COMMIT_VALIDATOR"; MOUNT_POLICY = "MOUNT_POLICY"; OUTPUT_GATE = "OUTPUT_GATE"; PURGE_ENGINE = "PURGE_ENGINE"; SESSION_CONTEXT = "SESSION_CONTEXT"; SAFETY_HANDLER = "SAFETY_HANDLER"
class SecurityOutcome(StrEnum): PASS = "PASS"; FAIL = "FAIL"; NOT_APPLICABLE = "NOT_APPLICABLE"
class ArchitecturalOutcome(StrEnum): PASS = "PASS"; DEGRADED = "DEGRADED"; FAIL = "FAIL"; UNDEFINED = "UNDEFINED"
class ValueStorageClass(StrEnum): INLINE_NON_SENSITIVE = "INLINE_NON_SENSITIVE"; VAULT_REF = "VAULT_REF"; NONE = "NONE"
