from typing import Protocol, List, Optional, Dict, Any

class BranchRepository(Protocol):
    def get_branch(self, branch_id: str) -> Optional[Dict[str, Any]]: ...
    def create_branch(self, branch_id: str, name: str) -> None: ...

class CoreRepository(Protocol):
    def get_snapshot(self, snapshot_id: str) -> Optional[Dict[str, Any]]: ...

class PolicyRepository(Protocol):
    def get_policy(self, policy_id: str) -> Optional[Dict[str, Any]]: ...

class EvidenceRepository(Protocol):
    def get_evidence(self, evidence_id: str) -> Optional[Dict[str, Any]]: ...
    def create_evidence(self, data: Dict[str, Any]) -> None: ...

class PatchRepository(Protocol):
    def get_patch(self, patch_id: str) -> Optional[Dict[str, Any]]: ...
    def create_patch(self, patch_data: Dict[str, Any], operations: List[Dict[str, Any]]) -> None: ...
    def get_patch_by_hash(self, patch_hash: str) -> List[Dict[str, Any]]: ...

class AuditRepository(Protocol):
    def get_audit(self, audit_id: str) -> Optional[Dict[str, Any]]: ...
    def create_audit(self, data: Dict[str, Any]) -> None: ...

class CommitRepository(Protocol):
    def get_commit(self, commit_id: str) -> Optional[Dict[str, Any]]: ...
    def create_commit(self, commit_data: Dict[str, Any]) -> None: ...

class MemoryRepository(Protocol):
    def get_record(self, record_id: str) -> Optional[Dict[str, Any]]: ...
    def get_active_operational(self, branch_id: str, semantic_key: str) -> Optional[Dict[str, Any]]: ...
    def get_active_personal(self, semantic_key: str) -> Optional[Dict[str, Any]]: ...
    def create_record(self, record_data: Dict[str, Any]) -> None: ...
    def update_record_status(self, record_id: str, status: str, superseded_by: Optional[str] = None) -> None: ...
    def purge_personal_record(self, record_id: str) -> None: ...

class LeaseRepository(Protocol):
    def get_lease(self, lease_id: str) -> Optional[Dict[str, Any]]: ...

class PurgeRepository(Protocol):
    def create_purge_job(self, job_data: Dict[str, Any]) -> None: ...

class TelemetryRepository(Protocol):
    def log_detection(self, event_data: Dict[str, Any]) -> None: ...
