from typing import Protocol, List, Optional
from uuid import UUID
from datetime import datetime

from memory_agent.domain.models import (
    Branch,
    CoreSnapshot,
    PolicySnapshot,
    EvidenceRecord,
    CognitiveStatePatch,
    AuditResult,
    CommitRecord,
    MemoryRecord,
    AccessLease,
    PurgeJob,
    DetectionEvent,
    PayloadObject
)
from memory_agent.domain.enums import RecordStatus, PurgeStatus

class BranchRepository(Protocol):
    def get_branch(self, branch_id: UUID) -> Optional[Branch]: ...
    def create_branch(self, branch: Branch) -> None: ...

class CoreRepository(Protocol):
    def get_snapshot(self, core_version: int) -> Optional[CoreSnapshot]: ...

class PolicyRepository(Protocol):
    def get_policy(self, policy_snapshot_id: UUID) -> Optional[PolicySnapshot]: ...

class EvidenceRepository(Protocol):
    def get_evidence(self, evidence_id: UUID) -> Optional[EvidenceRecord]: ...
    def create_evidence(self, data: EvidenceRecord) -> None: ...

class PatchRepository(Protocol):
    def get_patch(self, patch_id: UUID) -> Optional[CognitiveStatePatch]: ...
    def create_patch(self, patch_data: CognitiveStatePatch) -> None: ...
    def get_patch_by_hash(self, patch_hash: str) -> List[CognitiveStatePatch]: ...

class AuditRepository(Protocol):
    def get_audit(self, audit_id: UUID) -> Optional[AuditResult]: ...
    def create_audit(self, data: AuditResult) -> None: ...

class CommitRepository(Protocol):
    def get_commit(self, commit_id: UUID) -> Optional[CommitRecord]: ...
    def create_commit(self, commit_data: CommitRecord) -> None: ...

class MemoryRepository(Protocol):
    def get_record(self, record_id: UUID) -> Optional[MemoryRecord]: ...
    def get_active_operational(self, branch_id: UUID, semantic_key: str) -> Optional[MemoryRecord]: ...
    def get_active_personal(self, semantic_key: str) -> Optional[MemoryRecord]: ...
    def create_record(self, record_data: MemoryRecord) -> None: ...
    def update_record_status(self, record_id: UUID, status: RecordStatus, superseded_by: Optional[UUID] = None) -> None: ...
    def purge_personal_record(self, record_id: UUID) -> None: ...

class LeaseRepository(Protocol):
    def get_lease(self, lease_id: UUID) -> Optional[AccessLease]: ...
    def create_lease(self, lease_data: AccessLease) -> None: ...
    def revoke_lease(self, lease_id: UUID, revoked_at: datetime) -> None: ...

class PurgeRepository(Protocol):
    def create_purge_job(self, job_data: PurgeJob) -> None: ...
    def update_purge_job(self, job_id: UUID, status: PurgeStatus, completed_at: Optional[datetime] = None) -> None: ...

class TelemetryRepository(Protocol):
    def log_detection(self, event_data: DetectionEvent) -> None: ...

class PayloadRepository(Protocol):
    def get_payload(self, payload_id: UUID) -> Optional[PayloadObject]: ...
    def create_payload(self, payload_data: PayloadObject) -> None: ...
    def mark_destroyed(self, payload_id: UUID, destroyed_at: datetime) -> None: ...

class VaultRepository(Protocol):
    def store_ciphertext(self, payload_id: UUID, ciphertext: bytes) -> str: ...
    def retrieve_ciphertext(self, location: str) -> bytes: ...
    def delete_ciphertext(self, location: str) -> None: ...
