#!/usr/bin/env node
// CodeHive Coordination Listener
// Node 21+ required — WebSocket is global, no require('ws') needed
//
// Generated by hive init for project "memory-project".
// Override via PROJECT_ID env.
//
// Modes:
//   blocking (default): node listener.js
//     Connects to the project's WebSocket channel. Blocks until a message
//     arrives. Prints the message to stdout, exits 0. Use via spawn_subagent.
//
//   reactive: LISTEN_MODE=reactive node listener.js &
//     Stays connected forever, prints each message to stdout.
//     For Reactive Wakeup platforms (Antigravity).

const PROJECT_ID = process.env.PROJECT_ID || 'memory-project';
const ROOM_ID = process.env.ROOM_ID || `coordination::${PROJECT_ID}`;
const WS_URL = process.env.WS_URL || `ws://localhost:${process.env.PORT || 3000}/ws?roomId=${ROOM_ID}`;
const MODE = (process.env.LISTEN_MODE || 'blocking').toLowerCase();
const MAX_RETRIES = 15;
const BASE_DELAY = 1000;

let retries = 0;

function handleMessage(event) {
  try {
    const d = JSON.parse(event.data);
    if (d.type !== 'message_sent') return;
    const msg = d.payload?.message ?? '';
    if (!msg) return;
    console.log(msg);
    if (MODE === 'blocking') {
      ws.close();
      process.exit(0);
    }
  } catch {}
}

let ws;

function connect() {
  ws = new WebSocket(WS_URL);
  ws.onmessage = handleMessage;
  ws.onerror = () => {};

  ws.onclose = () => {
    if (MODE === 'reactive') {
      if (retries < MAX_RETRIES) {
        const delay = BASE_DELAY * Math.pow(2, retries);
        retries++;
        setTimeout(connect, delay);
      }
      return;
    }
    process.exit(1);
  };
}

connect();